#!/usr/bin/bash

# Created by: Stephen P. Vicchio 

# This script submits all PBS files named properly to Flux. 
#
# Note that the job type is just used to create the PBS file.
# The job type will no alter the gaussian input file. 
#

run_type=$1

if [[ ${run_type} == 'rerun' ]]; then 
	for file_sub in $(find . \( ! -name . -prune \) -type f -iname 'PBS-*_rerun*'); do
                qsub ${file_sub}
	done
elif [[ ${run_type} == 'none' ]]; then
    keyword=$2
	for file_sub in $(find . \( ! -name . -prune \) -type f -iname "PBS-*${keyword}*"); do
                qsub ${file_sub}
	done
else
	for file_sub in $(find . \( ! -name . -prune \) -type f -iname 'PBS-*'); do
		qsub ${file_sub} 
	done
fi

