#!/usr/bin/bash 

# Prints the filename and energy (if any) for each log file found starting
# from the current directory.

molecule_type=$1

if [ "${molecule_type}" == 'oxane' ] ; then 
	status_build=0
	num_atoms=16
	buffer_lines=4
elif [ "${molecule_type}" == 'bxyl' ] ;  then 
	status_build=0
	num_atoms=20
	buffer_lines=4
else
	echo
	echo "The molecule type is not found in this script"
	echo
	status_build=1
fi 

lines_grab=$((num_atoms + buffer_lines))


if [ ${status_build} == 1 ] ; then 
	exit
elif [ ${status_build} == 0 ] ; then 
	# For each file type ending in .log
	for log in $(find . -type f -iname '*.log'); do
        	filename="${log%.*}.xyz"
        	echo "     ${num_atoms}" > $filename
        	echo $log >> $filename
        	grep -A $lines_grab 'Input orientation:' $log | tail -${num_atoms} | awk '{print "  " $2 "  " $4 "  " $5 "  " $6}' >> $filename
	done
fi



