#!/usr/bin/bash

# Created by: Stephen P. Vicchio 

# The purpose of this script is to create a PBS for a job 
# submission onto Flux. 
#
# The following input is needed:
# $1 - molecule 
# $2 - job type (freeze, relax, TS) 
# $3 - level of theory (B3LYP, am1, pbe)
# 
# This script creates a COM file for Gaussian input (relaxed run)
# and generates the necessary PBS file. The script deals with a 
# tpl file, that can be found in the location listed below (tpl). 
# If any error arise from the script, check on the tpl file. 

input_list=../y0-input_list.txt
level_of_theory=$(head -n 1 ../y0-level_of_theory_basis_set.txt)

tpl=/home/vicchio/puckering/z_tpl/
template_file_oxane=gaussian-chk_run-optall_localmin-tpl_oxane.txt
template_file_prefrozen=gaussian-chk_run-optall_localmin-tpl_prefrozen.txt

molecule=$1
test_type=$2
short_level_of_theory=$3

cores_per_node=1
memory_job=15
total_memory=$(echo ${cores_per_node} ${memory_job} | awk '{ print $1*$2 }' )



mkdir /scratch/hbmayes_fluxod/vicchio/${1}-${2}_${3}

if [ ${molecule} == "oxane" ] ; then 

	for file_unedit in $( <$input_list); do 

		file=${file_unedit%.com}	

######## Moves over the checkpoint to create the new checkpoint file 

		#cp /scratch/hbmayes_fluxod/vicchio/${1}-freeze_${3}/${1}-${file}-freeze_${3}.chk /scratch/hbmayes_fluxod/vicchio/${1}-${2}_${3}/${1}-${file}-freeze_${3}-${2}_${3}.chk

######## The section below updates the Gaussian Input File

        sed -e "s/\$memory/${total_memory}/g" $tpl/${template_file_oxane} > temp1.com
        sed -e "s/\$num_procs/${cores_per_node}/g" temp1.com >> temp2.com
        sed -e "s/\$folder_old/${1}-freeze_${3}/g" temp2.com >> temp3.com
        sed -e "s/\$old_check/${1}-${file}-freeze_${3}.chk/g" temp3.com >> temp4.com
		sed -e "s/\$chkfile/${molecule}-${file}-freeze_${short_level_of_theory}-${test_type}_${short_level_of_theory}.chk/g" temp4.com >> temp5.com
  		sed -e "s/\$folder/${molecule}-${test_type}_${3}/g" temp5.com >> temp6.com
		sed -e "s/level_of_theory/${level_of_theory}/g" temp6.com >> $temp7.com

		mv temp7.com ${file}.com
	
		rm temp*.com

######## The section below creates the PBS file for submission on flux

		sed -e "s/molecule/${molecule}/g" $tpl/gaussian-PBS-tpl.txt > temp1.txt
  		sed -e "s/study/${2}/g" temp1.txt >> temp2.txt
		sed -e "s/level_of_theory_short/${short_level_of_theory}/g" temp2.txt >> temp3.txt
		sed -e "s/conform/${file}/g" temp3.txt >> temp4.txt
 		sed -e "s/gauss-log/${1}-${file}-freeze_${3}-${2}_${3}/g" temp4.txt >> temp5.txt
 		sed -e "s/\$num_proc/${cores_per_node}/g" temp5.txt >> temp6.txt
        sed -e "s/\$pmemory/${memory_job}/g" temp6.txt >> temp7.txt

	    mv temp7.txt PBS-${2}-${file}.txt

		rm temp*.txt
	done

else 
	for file_unedit in $( <$input_list); do
                file=${file_unedit%.xyz}

######## The section below updates the Gaussian Input File
		head -n 2 $tpl/${template_file_prefrozen} > ${file}-temp1.com 
		echo >> ${file}-temp1.com
		echo "From ${file_unedit}" >> ${file}-temp1.com
		echo >> ${file}-temp1.com
		echo "0  1" >> ${file}-temp1.com
		cat ../0_initial-coordinates/${file_unedit} | sed '1,2d' >> ${file}-temp1.com
		echo >> ${file}-temp1.com
		tail -n 5 $tpl/${template_file_prefrozen} >> ${file}-temp1.com  


                sed -e "s/\$chkfile/${file}-${test_type}_${short_level_of_theory}.chk/g" ${file}-temp1.com >> ${file}-temp.com
                sed -e "s/\$folder/${molecule}-${test_type}_${3}/g" ${file}-temp.com >> ${file}-temp2.com
                sed -e "s/level_of_theory/${level_of_theory}/g" ${file}-temp2.com >> ${file}-temp-final.com

                mv ${file}-temp-final.com ${file}.com

                rm ${file}-temp*

######## The section below creates the PBS file for submission on flux

                sed -e "s/molecule/${molecule}/g" $tpl/gaussian-PBS-tpl.txt > PBS-$2-${file}.txt
                sed -e "s/study/${2}/g" PBS-$2-${file}.txt >> PBS-$2-${file}-temp1.txt
                sed -e "s/level_of_theory_short/${short_level_of_theory}/g" PBS-$2-${file}-temp1.txt >> PBS-$2-${file}-temp2.txt
                sed -e "s/conform/${file}/g" PBS-$2-${file}-temp2.txt > PBS-$2-${file}-temp3.txt
                sed -e "s/gauss-log/${file}-${2}_${3}/g" PBS-${2}-${file}-temp3.txt > PBS-${2}-${file}.txt

                rm PBS-$2-${file}-temp*
        done
fi

