#!/usr/bin/bash

# Created by: Stephen P. Vicchio 

# The purpose of this script is to create a PBS for a job 
# submission onto Flux and local min run files.  
#
# The following input is needed:
# $1 - molecule 
# $2 - job type (freeze, relax, TS, emin) 
# $3 - level of theory (B3LYP, am1, pbe)
# 
# This script creates a COM file for Gaussian input (relaxed run)
# and generates the necessary PBS file. The script deals with a 
# tpl file, that can be found in the location listed below (tpl). 
# If any error arise from the script, check on the tpl file. 

molecule=$1
test_type=$2
short_level_of_theory=$3

z04-check-normal-termination ${molecule} ${test_type} ${short_level_of_theory}

failure=out-failure-${1}-${2}-${3}.txt
results_location=/home/vicchio/puckering/zz_results

if [ "${molecule}" == 'oxane' ] ; then
    mole_folder=1_oxane
elif [ "${molecule}" == 'bxyl' ] ;  then
	mole_folder=2_bxyl
else
	echo
	echo "The molecule type is not found in this script"
fi

if [ ! -f ${failure} ]; then
	echo "No files failed! Performing hartree and xyz_cluster."
	echo
	echo "Please wait a few minutes............"
	echo

	if [[ ${molecule} == 'oxane' ]]; then
		results_folder=1_oxane
		hartree cpsnap -d $PWD > z_hartree_out-unsorted-${molecule}-${short_level_of_theory}.csv
		z05-grab_xyz_oxane ${molecule}
		xyz_cluster -s z_hartree_out-unsorted-${molecule}-${short_level_of_theory}.csv -t 0.01

	elif [[ ${molecule} == 'bxyl' ]]; then
		results_folder=2_bxyl
		hartree cpsnap -d $PWD > z_hartree_out-unsorted-${molecule}-${short_level_of_theory}.csv
		z05-grab_xyz_oxane ${molecule}
		xyz_cluster -s z_hartree_out-unsorted-${molecule}-${short_level_of_theory}.csv -t 0.1 -r '0,8,12,16,4,7'

	else
		echo "Need to add the molecule to the script!"
	fi

else
	echo 'There is a file that did not run properly!'
fi

mv z_cluster_z_hartree_out-unsorted-${molecule}-${short_level_of_theory}.csv z_cluster-sorted-TS-${molecule}-${short_level_of_theory}.csv

cp z_cluster-sorted-TS-${molecule}-${short_level_of_theory}.csv /home/vicchio/puckering/zz_results/${results_folder}/.


new_dir=/home/vicchio/puckering/zz_results/${results_folder}/${molecule}-${test_type}-${short_level_of_theory}

if [ ! -d ${new_dir} ]; then
    mkdir ${new_dir}
fi

ts_hartree_file=/home/vicchio/puckering/zz_results/${mole_folder}/z_cluster-sorted-TS-${molecule}-${short_level_of_theory}.csv

input_list=$( column -t -s ',' ${ts_hartree_file} | awk '{print $1}' )

for file in ${input_list}; do

    file1=${file%.log\"}
    file_org=${file1##\"}

   if [ "${file_org}" != "File" ]; then

        cp ${file_org}.log ${new_dir}/.
   fi
done










