#!/usr/bin/bash

# Created by: Stephen P. Vicchio 

# The purpose of this script is to create a PBS for a job 
# submission onto Flux. 
#
# The following input is needed:
# $1 - molecule 
# $2 - job type (freeze, relax, TS) 
# $3 - level of theory (B3LYP, am1, pbe)
# 
# This script creates a COM file for Gaussian input (relaxed run)
# and generates the necessary PBS file. The script deals with a 
# tpl file, that can be found in the location listed below (tpl). 
# If any error arise from the script, check on the tpl file. 

molecule=$1
test_type=$2
short_level_of_theory=$3 

level_of_theory=$(head -n 1 ../y0-level_of_theory_basis_set.txt)

tpl=/home/vicchio/puckering/z_tpl
template_file_forward=gaussian-chk_run-IRC-forward.txt
template_file_reverse=gaussian-chk_run-IRC-reverse.txt

cores_per_nodes=1
memory_job=25

if [ "${molecule}" == 'oxane' ] ; then
    mole_folder=1_oxane
elif [ "${molecule}" == 'bxyl' ] ;  then
	mole_folder=2_bxyl
else
	echo
	echo "The molecule type is not found in this script"
fi


ts_hartree_file=/home/vicchio/puckering/zz_results/${mole_folder}/z_cluster-sorted-TS-${molecule}-${short_level_of_theory}.csv

irc_forward=/scratch/hbmayes_fluxod/vicchio/${1}-${2}_${3}-forward
irc_backward=/scratch/hbmayes_fluxod/vicchio/${1}-${2}_${3}-reverse

if [ ! -d ${irc_forward} ]; then
    mkdir ${irc_forward}
fi

if [ ! -d ${irc_backward} ]; then
    mkdir ${irc_backward}
fi

echo ${molecule}

if [ ${molecule} == "oxane" ] ; then

    #input_list=../6_prod-run_TS/z_list_cluster-sorted-TS-${molecule}-${short_level_of_theory}.txt

    echo ${ts_hartree_file}

    input_list=$( column -t -s ',' ${ts_hartree_file} | awk '{print $1}' )

    echo ${input_list}

     for file in ${input_list}; do

        file1=${file%.log\"}
        file_org=${file1##\"}

          if [ "${file_org}" != "File" ]; then

            echo ${file_org}

        ########## IRC Information for the Forward Direction ##########

            new_filenamef=${file_org}-ircf

            ######## Moves over the checkpoint to create the new checkpoint file

            #cp /scratch/hbmayes_fluxod/vicchio/${1}-TS_${3}/${file_org}.chk /scratch/hbmayes_fluxod/vicchio/${1}-${2}_${3}-forward/${new_filenamef}_${3}.chk

           ######## The section below updates the Gaussian Input File

            old_check_file=/scratch/hbmayes_fluxod/vicchio/${1}-TS_${3}/${file_org}.chk
            new_check_file=/scratch/hbmayes_fluxod/vicchio/${1}-${2}_${3}-forward/${new_filenamef}_${3}.chk

            sed -e "s/\$memory/${memory_job}/g" $tpl/${template_file_forward} > temp4.com
            sed -e "s/\$num_procs/${cores_per_node}/g" temp4.com >> temp5.com
            sed -e "s/\$old_check/${old_check_file}/g" temp5.com >> temp6.com
            sed -e "s/\$chkfile/${new_check_file}/g" temp6.com >> temp1.com
            sed -e "s/\$folder/${molecule}-${test_type}_${3}-forward/g" temp1.com >> temp2.com
            sed -e "s/level_of_theory/${level_of_theory}/g" temp2.com >> temp3.com

            mv temp3.com ${new_filenamef}.com

            rm *temp*

           ######## The section below creates the PBS file for submission on flux

            sed -e "s/molecule/${molecule}/g" $tpl/gaussian-PBS-tpl_IRC.txt > PBS-temp1.txt
            sed -e "s/study/${2}/g" PBS-temp1.txt >> PBS-temp2.txt
            sed -e "s/level_of_theory_short/${short_level_of_theory}/g" PBS-temp2.txt >> PBS-temp3.txt
            sed -e "s/conform/${new_filenamef}/g" PBS-temp3.txt >> PBS-temp4.txt
            sed -e "s/\$num_proc/${cores_per_node}/g" PBS-temp4.txt >> PBS-temp5.txt

            sed -e "s/gauss-log/${new_filenamef}_${3}/g" PBS-temp5.txt > PBS-${2}-${new_filenamef}.txt

            rm PBS-temp*.txt


        ########## IRC Information for the Reverse Direction ##########

            new_filenamer=${file_org}-ircr

        ######## Moves over the checkpoint to create the new checkpoint file

            cp /scratch/hbmayes_fluxod/vicchio/${1}-TS_${3}/${file_org}.chk /scratch/hbmayes_fluxod/vicchio/${1}-${2}_${3}-reverse/${new_filenamer}_${3}.chk

         ######## The section below updates the Gaussian Input File

            sed -e "s/\$chkfile/${file_org}-${2}-r_${3}.chk/g" $tpl/${template_file_reverse} > temp1.com
            sed -e "s/\$folder/${molecule}-${test_type}_${3}-reverse/g" temp1.com >> temp2.com
            sed -e "s/level_of_theory/${level_of_theory}/g" temp2.com >> temp3.com

            mv temp3.com ${new_filenamer}.com

            rm *temp*

           ######## The section below creates the PBS file for submission on flux

            sed -e "s/molecule/${molecule}/g" $tpl/gaussian-PBS-tpl.txt > PBS-temp1.txt
            sed -e "s/study/${2}/g" PBS-temp1.txt >> PBS-temp2.txt
            sed -e "s/level_of_theory_short/${short_level_of_theory}/g" PBS-temp2.txt >> PBS-temp3.txt
            sed -e "s/conform/${new_filenamer}/g" PBS-temp3.txt >> PBS-temp4.txt
            sed -e "s/gauss-log/${new_filenamer}_${3}/g" PBS-temp4.txt > PBS-${2}-${new_filenamer}.txt

            rm PBS-temp*.txt
        fi
    done

else

    input_list=$( column -t -s ',' ${ts_hartree_file} | awk '{print $1}' )

    for file in ${input_list}; do

        file1=${file%.log\"}
        file_org=${file1##\"}

       if [ "${file_org}" != "File" ]; then

            new_filenamef=${file_org}-ircf

            ########## IRC Information for the Forward Direction ##########

            ######## Moves over the checkpoint to create the new checkpoint file

            cp /scratch/hbmayes_fluxod/vicchio/${1}-TS_${3}/${file_org}.chk /scratch/hbmayes_fluxod/vicchio/${1}-${2}_${3}-forward/${new_filenamef}_${3}.chk

            ######## The section below updates the Gaussian Input File

            sed -e "s/\$chkfile/${new_filenamef}_${3}.chk/g" $tpl/${template_file_forward} > file-temp.com
            sed -e "s/\$folder/${molecule}-${test_type}_${3}-forward/g" file-temp.com >> file-temp1.com
            sed -e "s/level_of_theory/${level_of_theory}/g" file-temp1.com >> file-temp2.com

            mv file-temp2.com ${new_filenamef}.com

            rm file-temp*.com

            ######## The section below creates the PBS file for submission on flux

            sed -e "s/molecule/${molecule}/g" $tpl/gaussian-PBS-tpl.txt > PBS-temp1.txt
            sed -e "s/study/${2}/g" PBS-temp1.txt >> PBS-temp2.txt
            sed -e "s/level_of_theory_short/${short_level_of_theory}/g" PBS-temp2.txt >> PBS-temp3.txt
            sed -e "s/conform/${new_filenamef}/g" PBS-temp3.txt > PBS-temp4.txt
            sed -e "s/gauss-log/${new_filenamef}_${3}/g" PBS-temp4.txt > PBS-${2}-${new_filenamef}.txt

            rm PBS-temp*

            new_filenamer=${file_org}-ircr

            ########## IRC Information for the Forward Direction ##########

            ######## Moves over the checkpoint to create the new checkpoint file

            cp /scratch/hbmayes_fluxod/vicchio/${1}-TS_${3}/${file_org}.chk /scratch/hbmayes_fluxod/vicchio/${1}-${2}_${3}-reverse/${new_filenamer}_${3}.chk

            ######## The section below updates the Gaussian Input File

            sed -e "s/\$chkfile/${new_filenamer}_${3}.chk/g" $tpl/${template_file_reverse} > file-temp.com
            sed -e "s/\$folder/${molecule}-${test_type}_${3}-reverse/g" file-temp.com >> file-temp1.com
            sed -e "s/level_of_theory/${level_of_theory}/g" file-temp1.com >> file-temp2.com

            mv file-temp2.com ${new_filenamer}.com

            rm file-temp*.com

            ######## The section below creates the PBS file for submission on flux

            sed -e "s/molecule/${molecule}/g" $tpl/gaussian-PBS-tpl.txt > PBS-temp1.txt
            sed -e "s/study/${2}/g" PBS-temp1.txt >> PBS-temp2.txt
            sed -e "s/level_of_theory_short/${short_level_of_theory}/g" PBS-temp2.txt >> PBS-temp3.txt
            sed -e "s/conform/${new_filenamer}/g" PBS-temp3.txt > PBS-temp4.txt
            sed -e "s/gauss-log/${new_filenamer}_${3}/g" PBS-temp4.txt > PBS-${2}-${new_filenamer}.txt

            rm PBS-temp*
        fi
    done
fi


