#!/usr/bin/bash

# Created by: Stephen P. Vicchio 

# The purpose of this script is to create a PBS for a job 
# submission onto Flux. 
#
# The following input is needed:
# $1 - molecule 
# $2 - job type (freeze, relax, TS) 
# $3 - level of theory (B3LYP, am1, pbe)
# 
# This script creates a COM file for Gaussian input (relaxed run)
# and generates the necessary PBS file. The script deals with a 
# tpl file, that can be found in the location listed below (tpl). 
# If any error arise from the script, check on the tpl file. 

molecule=$1
test_type=$2
short_level_of_theory=$3 

level_of_theory=$(head -n 1 ../y0-level_of_theory_basis_set.txt)

tpl=/home/vicchio/puckering/z_tpl
template_file_forward=gaussian-chk_run-IRC-forward.txt
template_file_reverse=gaussian-chk_run-IRC-reverse.txt

if [ "${molecule}" == 'oxane' ] ; then
    mole_folder=1_oxane
elif [ "${molecule}" == 'bxyl' ] ;  then
	mole_folder=2_bxyl
else
	echo
	echo "The molecule type is not found in this script"
fi


ts_hartree_file=/home/vicchio/puckering/zz_results/${mole_folder}/z_cluster-sorted-TS-${molecule}-${short_level_of_theory}.csv


irc_forward=/scratch/hbmayes_fluxod/vicchio/${1}-${2}_${3}-forward
irc_backward=/scratch/hbmayes_fluxod/vicchio/${1}-${2}_${3}-reverse

if [ ! -d ${irc_forward} ]; then
    mkdir ${irc_forward}
fi

if [ ! -d ${irc_backward} ]; then
    mkdir ${irc_backward}
fi

if [ ${molecule} == "oxane" ] ; then

    input_list=../6_prod-run_TS/z_list_cluster-sorted-TS-${molecule}-${short_level_of_theory}.txt

    while IFS= read -r cmd; do
        structure_id=$(printf '%s\n' "$cmd" | cut -c 7-9 | sed 's/-$//')
        echo ${structure_id}
        file=${structure_id}

    ########## IRC Information for the Forward Direction ##########

    ######## Moves over the checkpoint to create the new checkpoint file

    cp /scratch/hbmayes_fluxod/vicchio/${1}-TS_${3}/${1}-${file}-freeze_${3}-TS_${3}.chk /scratch/hbmayes_fluxod/vicchio/${1}-${2}_${3}-forward/${1}-${file}-freeze_${3}-${2}-f_${3}.chk

    ######## The section below updates the Gaussian Input File

    sed -e "s/\$chkfile/${1}-${file}-freeze_${3}-${2}-f_${3}.chk/g" $tpl/${template_file_forward} > ${file}.com
    sed -e "s/\$folder/${molecule}-${test_type}_${3}-forward/g" ${file}.com >> ${file}-temp1.com
    sed -e "s/level_of_theory/${level_of_theory}/g" ${file}-temp1.com >> ${file}-temp.com

    mv ${file}-temp.com ${file}-f.com

    rm ${file}-temp1.com

    ######## The section below creates the PBS file for submission on flux

    sed -e "s/molecule/${molecule}/g" $tpl/gaussian-PBS-tpl.txt > PBS-$2-${file}.txt
    sed -e "s/study/${2}/g" PBS-$2-${file}.txt >> PBS-$2-${file}-temp1.txt
    sed -e "s/level_of_theory_short/${short_level_of_theory}/g" PBS-$2-${file}-temp1.txt >> PBS-$2-${file}-temp2.txt
    sed -e "s/conform/${file}-f/g" PBS-$2-${file}-temp2.txt > PBS-$2-${file}-temp3.txt
    sed -e "s/gauss-log/${1}-${file}-freeze_${3}-${2}-forward-${3}/g" PBS-${2}-${file}-temp3.txt > PBS-${2}-${file}-f.txt

    rm PBS-$2-${file}-temp*


    ########## IRC Information for the Reverse Direction ##########

    ######## Moves over the checkpoint to create the new checkpoint file

    cp /scratch/hbmayes_fluxod/vicchio/${1}-TS_${3}/${1}-${file}-freeze_${3}-TS_${3}.chk /scratch/hbmayes_fluxod/vicchio/${1}-${2}_${3}-reverse/${1}-${file}-freeze_${3}-${2}-r_${3}.chk

    ######## The section below updates the Gaussian Input File

    sed -e "s/\$chkfile/${1}-${file}-freeze_${3}-${2}-r_${3}.chk/g" $tpl/${template_file_reverse} > ${file}.com
    sed -e "s/\$folder/${molecule}-${test_type}_${3}-reverse/g" ${file}.com >> ${file}-temp1.com
    sed -e "s/level_of_theory/${level_of_theory}/g" ${file}-temp1.com >> ${file}-temp.com

    mv ${file}-temp.com ${file}-r.com

    rm ${file}-temp1.com

    ######## The section below creates the PBS file for submission on flux

    sed -e "s/molecule/${molecule}/g" $tpl/gaussian-PBS-tpl.txt > PBS-$2-${file}.txt
    sed -e "s/study/${2}/g" PBS-$2-${file}.txt >> PBS-$2-${file}-temp1.txt
    sed -e "s/level_of_theory_short/${short_level_of_theory}/g" PBS-$2-${file}-temp1.txt >> PBS-$2-${file}-temp2.txt
    sed -e "s/conform/${file}-r/g" PBS-$2-${file}-temp2.txt > PBS-$2-${file}-temp3.txt
    sed -e "s/gauss-log/${1}-${file}-freeze_${3}-${2}-reverse_${3}/g" PBS-${2}-${file}-temp3.txt > PBS-${2}-${file}-r.txt

    rm PBS-$2-${file}-temp*

    rm PBS-${2}-${file}.txt
    rm ${file}.com

    done < "${input_list}"

else

    input_list=$( column -t -s ',' ${ts_hartree_file} | awk '{print $1}' )

    for file in ${input_list}; do

        file1=${file%.log\"}
        file_org=${file1##\"}

       if [ "${file_org}" != "File" ]; then

            new_filenamef=${file_org}-ircf

            ########## IRC Information for the Forward Direction ##########

            ######## Moves over the checkpoint to create the new checkpoint file

            cp /scratch/hbmayes_fluxod/vicchio/${1}-TS_${3}/${file_org}.chk /scratch/hbmayes_fluxod/vicchio/${1}-${2}_${3}-forward/${new_filenamef}_${3}.chk

            ######## The section below updates the Gaussian Input File

            sed -e "s/\$chkfile/${new_filenamef}_${3}.chk/g" $tpl/${template_file_forward} > file-temp.com
            sed -e "s/\$folder/${molecule}-${test_type}_${3}-forward/g" file-temp.com >> file-temp1.com
            sed -e "s/level_of_theory/${level_of_theory}/g" file-temp1.com >> file-temp2.com

            mv file-temp2.com ${new_filenamef}.com

            rm file-temp*.com

            ######## The section below creates the PBS file for submission on flux

            sed -e "s/molecule/${molecule}/g" $tpl/gaussian-PBS-tpl.txt > PBS-temp1.txt
            sed -e "s/study/${2}/g" PBS-temp1.txt >> PBS-temp2.txt
            sed -e "s/level_of_theory_short/${short_level_of_theory}/g" PBS-temp2.txt >> PBS-temp3.txt
            sed -e "s/conform/${new_filenamef}-f/g" PBS-temp3.txt > PBS-temp4.txt
            sed -e "s/gauss-log/${1}-${new_filenamef}-f-${3}/g" PBS-temp4.txt > PBS-${2}-${new_filenamef}.txt

            rm PBS-temp*

            new_filenamer=${file_org}-ircr

            ########## IRC Information for the Forward Direction ##########

            ######## Moves over the checkpoint to create the new checkpoint file

            cp /scratch/hbmayes_fluxod/vicchio/${1}-TS_${3}/${file_org}.chk /scratch/hbmayes_fluxod/vicchio/${1}-${2}_${3}-reverse/${new_filenamer}_${3}.chk

            ######## The section below updates the Gaussian Input File

            sed -e "s/\$chkfile/${new_filenamer}_${3}.chk/g" $tpl/${template_file_reverse} > file-temp.com
            sed -e "s/\$folder/${molecule}-${test_type}_${3}-reverse/g" file-temp.com >> file-temp1.com
            sed -e "s/level_of_theory/${level_of_theory}/g" file-temp1.com >> file-temp2.com

            mv file-temp2.com ${new_filenamer}.com

            rm file-temp*.com

            ######## The section below creates the PBS file for submission on flux

            sed -e "s/molecule/${molecule}/g" $tpl/gaussian-PBS-tpl.txt > PBS-temp1.txt
            sed -e "s/study/${2}/g" PBS-temp1.txt >> PBS-temp2.txt
            sed -e "s/level_of_theory_short/${short_level_of_theory}/g" PBS-temp2.txt >> PBS-temp3.txt
            sed -e "s/conform/${new_filenamer}/g" PBS-temp3.txt > PBS-temp4.txt
            sed -e "s/gauss-log/${new_filenamer}_${3}/g" PBS-temp4.txt > PBS-${2}-${new_filenamer}.txt

            rm PBS-temp*
        fi
    done
fi


