#!/usr/bin/bash

# Created by: Stephen P. Vicchio 

# The purpose of this script is to create a PBS for a job 
# submission onto Flux. 
#
# The following input is needed:
# $1 - molecule 
# $2 - job type (freeze, relax, TS) 
# $3 - level of theory (B3LYP, am1, pbe)
# 
# This script creates a COM file for Gaussian input (relaxed run)
# and generates the necessary PBS file. The script deals with a 
# tpl file, that can be found in the location listed below (tpl). 
# If any error arise from the script, check on the tpl file. 


input_files=$(ls ../6_prod-run_IRC/*.log > y0-input_list.txt)
input_list=y0-input_list.txt
level_of_theory=$(head -n 1 ../y0-level_of_theory_basis_set.txt)

tpl=/home/vicchio/puckering/z_tpl
template_file=gaussian-chk_run-optall_localmin-tpl_lmirc.txt
scratch=/scratch/hbmayes_fluxod/vicchio

molecule=$1
test_type=$2
short_level_of_theory=$3 

cores_per_node=1
memory_job=25
total_memory=$(echo ${cores_per_node} ${memory_job} | awk '{ print $1*$2 }' )

if [ ! -d /scratch/hbmayes_fluxod/vicchio/${1}-${2}_${3} ]; then
    mkdir /scratch/hbmayes_fluxod/vicchio/${1}-${2}_${3}
fi

while IFS= read -r cmd; do

######## Organizes the file naming information
	file_orgin_long=$(printf '%s\n' "$cmd" | cut -c 19-100 | sed 's/-$//' ) 
	file_orgin=${file_orgin_long%.log}	

    echo ${file_orgin}

######## Moves over the checkpoint to create the new checkpoint file 

    if [[ ${file_orgin} == *"ircf"* ]]; then
        folder_loc_old=${molecule}-IRC_${short_level_of_theory}-forward
        folder_loc_new=${molecule}-${test_type}_${short_level_of_theory}
#        cp ${scratch}/${folder_loc_old}/${file_orgin}.chk ${scratch}/${folder_loc_new}/${file_orgin}.chk

    elif [[ ${file_orgin} == *"ircr"* ]]; then
        folder_loc_old=${molecule}-IRC_${short_level_of_theory}-reverse
        folder_loc_new=${molecule}-${test_type}_${short_level_of_theory}
#        cp ${scratch}/${folder_loc_old}/${file_orgin}.chk ${scratch}/${folder_loc_new}/${file_orgin}.chk

    else
        echo "Something is wrong"
    fi

	file=${file_orgin}

######## The section below updates the Gaussian Input File

    sed -e "s/\$memory/${total_memory}/g" $tpl/${template_file} > temp1.com
    sed -e "s/\$num_procs/${cores_per_node}/g" temp1.com >> temp2.com
    sed -e "s/\$folder_old/${folder_loc_old}/g" temp2.com >> temp3.com
    sed -e "s/\$old_check/${file_orgin}.chk/g" temp3.com >> temp4.com
    sed -e "s/\$chkfile/${file_orgin}-lmirc.chk/g" temp4.com >> temp5.com
    sed -e "s/\$folder/${folder_loc_new}/g" temp5.com >> temp6.com
    sed -e "s/level_of_theory/${level_of_theory}/g" temp6.com >> temp7.com

	mv temp7.com ${file}.com
	
	rm temp*.com

######## The section below creates the PBS file for submission on flux

    sed -e "s/molecule/${molecule}/g" $tpl/gaussian-PBS-tpl_IRC.txt > PBS-temp1.txt
    sed -e "s/study/${test_type}/g" PBS-temp1.txt >> PBS-temp2.txt
    sed -e "s/level_of_theory_short/${short_level_of_theory}/g" PBS-temp2.txt >> PBS-temp3.txt
    sed -e "s/conform/${file}/g" PBS-temp3.txt >> PBS-temp4.txt
    sed -e "s/\$num_proc/${cores_per_node}/g" PBS-temp4.txt >> PBS-temp5.txt
    sed -e "s/\$pmemory/${memory_job}/g" PBS-temp5.txt >> PBS-temp6.txt
    sed -e "s/gauss-log/${file_orgin}-minIRC_${short_level_of_theory}/g" PBS-temp6.txt > PBS-${2}-${file}.txt

	rm PBS-temp*

done < "${input_list}"

