#!/usr/bin/bash

# Created by: Stephen P. Vicchio

# This script deletes a range of files on Flux.

lowerbound=$1
upperbound=$2

total_files_to_delete=$( echo "${upperbound}-${lowerbound}" | bc )

echo ${total_files_to_delete}

list_delete=$(seq ${total_files_to_delete})

echo ${list_delete}

for file_number in ${list_delete}; do

    echo ${file_number}

done

> list_count.txt

echo "I am outside"
for file_number in $( $list_count.txt); do
    echo "I am inside"
    echo ${file_number}
    echo ${lowerbound}
#    current_file_delete=$( ${file_number} + ${lowerbound})
    current_file_delete=$( echo "${lowerbound}+${file_number}-1" | bc )
    echo ${current_file_delete}

done

#rm list_count.txt
