#!/usr/bin/bash

# Created by: Stephen P. Vicchio

# The purpose of this script is generate the norm files for the different TS structures to perform an norm analysis.


molecule=${1}
job_type=${2}
level_theory=${3}

tpl_dict=/home/vicchio/puckering/z_tpl
tpl_file=gaussian-norm_TS.tpl
scratch_dict=/scratch/hbmayes_fluxod/vicchio
scratch_fold=${molecule}-${job_type}_${level_theory}
level_of_theory_real=$(head ../y0-level_of_theory_basis_set.txt)


if [ "${molecule}" == 'oxane' ] ; then
    status_build=0
    mole_folder=1_oxane
elif [ "${molecule}" == 'bxyl' ] ;  then
	status_build=0
	mole_folder=2_bxyl
else
	echo
	echo "The molecule type is not found in this script"
	status_build=1
fi

ts_hartree_file=/home/vicchio/puckering/zz_results/${mole_folder}/z_cluster-sorted-TS-${molecule}-${level_theory}.csv

if [ ! -f "${ts_hartree_file}" ]; then
	echo
	echo "The hartree file for ${molecule} with ${level_theory} does not exist."
	echo
	exit
fi

if [ ! -d "${scratch_dict}/${scratch_fold}" ]; then
    mkdir ${scratch_dict}/${scratch_fold}
fi

input_list=$( column -t -s ',' ${ts_hartree_file} | awk '{print $1}' )

for file in ${input_list}; do

    file1=${file%.log\"}
    file_org=${file1##\"}

   if [ "${file_org}" != "File" ]; then

        new_filename=${file_org}_norm

        cp ${scratch_dict}/${molecule}-TS_${level_theory}/${file_org}.chk ${scratch_dict}/${scratch_fold}/${new_filename}.chk

        #### Creating the COM files for my jobs!

        sed -e "s/\$chkfile/${new_filename}.chk/g" ${tpl_dict}/${tpl_file} > ${new_filename}_temp.tmp
        sed -e "s/\$folder/${molecule}-${job_type}_${level_theory}/g" ${new_filename}_temp.tmp >> ${new_filename}_temp2.tmp
        sed -e "s/+leveltheory+/${level_of_theory_real}/g" ${new_filename}_temp2.tmp >> temp-final.tmp

        mv temp-final.tmp ${new_filename}.com

        rm *temp*


        #### Creating the PBS for my norm jobs!
        sed -e "s/molecule/${molecule}/g" ${tpl_dict}/gaussian-PBS-tpl.txt > PBS-temp.txt
        sed -e "s/study/${2}/g" PBS-temp.txt >> PBS-temp1.txt
        sed -e "s/level_of_theory_short/${level_theory}/g" PBS-temp1.txt >> PBS-temp2.txt
        sed -e "s/conform/${new_filename}/g" PBS-temp2.txt > PBS-temp3.txt
        sed -e "s/gauss-log/${new_filename}/g" PBS-temp3.txt > PBS-${2}-${new_filename}.txt

        rm PBS-temp*


    fi
done




