#!/usr/bin/bash

# Created by: Stephen P. Vicchio

# The purpose of this script is generate the norm files for the different TS structures to perform an norm analysis.


molecule=${1}
job_type=${2}
level_theory=${3}

tpl_dict=/home/vicchio/puckering/z_tpl
tpl_file=gaussian-norm_TS.tpl
scratch_dict=/scratch/hbmayes_fluxod/vicchio
scratch_fold=${molecule}-${job_type}_${level_theory}


if [ "${molecule}" == 'oxane' ] ; then
    status_build=0
    mole_folder=1_oxane
elif [ "${molecule}" == 'bxyl' ] ;  then
	status_build=0
	mole_folder=2_bxyl
else
	echo
	echo "The molecule type is not found in this script"
	status_build=1
fi

ts_hartree_file=/home/vicchio/puckering/zz_results/${mole_folder}/z_cluster-sorted-TS-${molecule}-${level_theory}.csv

if [ ! -f "${ts_hartree_file}" ]; then
	echo
	echo "The hartree file for ${molecule} with ${level_theory} does not exist."
	echo
	exit
fi

if [ ! -d "${scratch_dict}/${scratch_fold}" ]; then
    mkdir ${scratch_dict}/${scratch_fold}
fi

input_list=$( column -t -s ',' ${ts_hartree_file} | awk '{print $1}' )

for file in ${input_list}; do

    file1=${file%.log\"}
    file_org=${file1##\"}
    new_filename=${file_org}_norm.com

    echo ${scratch_dict}/${molecule}-TS-${level_theory}/${file_org}.log ${scratch_dict}/${scratch_fold}/${new_filename}

    echo ${tpl_dict}/${tpl_file} ${new_filename}


done




