#!/usr/bin/bash

# Created by: Stephen P. Vicchio

# The purpose of this script is to show the normal mode analysis from gaussian in a way
# that can be easiler seen.
#


molecule=${1}
job_type=${2}
short_level_theory=${3}

results_dirct=/home/vicchio/puckering/zz_results/2_bxyl
new_results=${molecule}-${job_type}-${short_level_theory}
out_dirct=9_hartree_norm

tpl=/home/vicchio/puckering/z_tpl
template_file_forward=gaussian-chk_run-IRC-forward.txt
template_file_reverse=gaussian-chk_run-IRC-reverse.txt


if [ "${molecule}" == 'oxane' ] ; then
    status_build=0
    mole_folder=1_oxane
elif [ "${molecule}" == 'bxyl' ] ;  then
	status_build=0
	mole_folder=2_bxyl
else
	echo
	echo "The molecule type is not found in this script"
	status_build=1
fi

if [ ${status_build} == "1" ]; then
	echo
	echo "Something isn't right with the script...the molecule"
	echo "may not be found!"
	echo
	exit
elif [ ${status_build} == "0" ]; then



    folder_location=/home/vicchio/puckering/${mole_folder}/${short_level_theory}
    level_theory=${folder_location}/y0-level_of_theory_basis_set.txt

    echo ${level_theory}


    if [ ! -d ../${out_dirct} ]; then
        mkdir ../9_hartree_norm
    fi

    hartree norm -d ../8_norm/. -o ../9_hartree_norm/.

    if [ ! -d ${results_dirct}/${new_results}/ ]; then
        mkdir ${results_dirct}/${new_results}/
        mkdir ${results_dirct}/${new_results}/hartree-files
        mkdir ${results_dirct}/${new_results}/log-files
    fi

    cp ${folder_location}/9_hartree_norm/*.txt ${results_dirct}/${new_results}/hartree-files
    cp ${folder_location}/8_norm/*.log ${results_dirct}/${new_results}/log-files
fi

cd ${folder_location}/9_hartree_norm/

ls *norm.txt > z_hartree_norm_analysis_${short_level_theory}.txt

norm_analysis -s z_hartree_norm_analysis_${short_level_theory}.txt -r '8,1,9,13,17,5'

mv z_norm-analysis_TS_exo_puckers_z_hartree_norm_analysis_am1.txt z_norm_analysis_list_exo-TS_${molecule}_${short_level_theory}.txt
mv z_norm-analysis_TS_ring_puckers_z_hartree_norm_analysis_am1.txt z_norm_analysis_list_ring-TS_${molecule}_${short_level_theory}.txt

if [ ! -d ${results_dirct}/${new_results}/log_norm_analysis/ ]; then
    mkdir ${results_dirct}/${new_results}/log_norm_analysis
fi

cp z_norm_analysis_list_ring-TS_${molecule}_${short_level_theory}.txt ${results_dirct}/${new_results}
cp z_norm_analysis_list_exo-TS_${molecule}_${short_level_theory}.txt ${results_dirct}/${new_results}





#################

# This part of the script prepares for the IRC calculations.

if [ ! -d /scratch/hbmayes_fluxod/vicchio/${1}-irc_${3} ]; then
    mkdir /scratch/hbmayes_fluxod/vicchio/${1}-irc_${3}
fi

cd ${folder_location}/6_prod-run_IRC

input_list=$( column -t -s '' ${results_dirct}/${new_results}/z_norm_analysis_list_ring-TS_${molecule}_${short_level_theory}.txt | awk '{print $1}' )

    for file in ${input_list}; do

        file1=${file%.log}

        echo ${file1}

       if [ "${file1}" != "File" ]; then

            new_filenamef=${file1}-ircf

            ########## IRC Information for the Forward Direction ##########

            ######## Moves over the checkpoint to create the new checkpoint file

            cp /scratch/hbmayes_fluxod/vicchio/${1}-norm_${3}/${file1}.chk /scratch/hbmayes_fluxod/vicchio/${1}-irc_${3}-forward/${new_filenamef}_${3}.chk

            ######## The section below updates the Gaussian Input File

            sed -e "s/\$chkfile/${new_filenamef}_${3}.chk/g" $tpl/${template_file_forward} > file-temp.com
            sed -e "s/\$folder/${molecule}-irc_${3}-forward/g" file-temp.com >> file-temp1.com
            sed -e "s/level_of_theory/${level_theory}/g" file-temp1.com >> file-temp2.com

            mv file-temp2.com ${folder_location}/6_prod-run_IRC/${new_filenamef}.com

            rm file-temp*.com

            ######## The section below creates the PBS file for submission on flux

            sed -e "s/molecule/${molecule}/g" $tpl/gaussian-PBS-tpl.txt > PBS-temp1.txt
            sed -e "s/study/${2}/g" PBS-temp1.txt >> PBS-temp2.txt
            sed -e "s/level_of_theory_short/${short_level_theory}/g" PBS-temp2.txt >> PBS-temp3.txt
            sed -e "s/conform/${new_filenamef}/g" PBS-temp3.txt > PBS-temp4.txt
            sed -e "s/gauss-log/${new_filenamef}_${3}/g" PBS-temp4.txt > ${folder_location}/6_prod-run_IRC/PBS-${2}-${new_filenamef}.txt

            rm PBS-temp*

            new_filenamer=${file1}-ircr

            ########## IRC Information for the Forward Direction ##########

            ######## Moves over the checkpoint to create the new checkpoint file

            cp /scratch/hbmayes_fluxod/vicchio/${1}-norm_${3}/${file1}.chk /scratch/hbmayes_fluxod/vicchio/${1}-irc_${3}-reverse/${new_filenamer}_${3}.chk

            ######## The section below updates the Gaussian Input File

            sed -e "s/\$chkfile/${new_filenamer}_${3}.chk/g" $tpl/${template_file_reverse} > file-temp.com
            sed -e "s/\$folder/${molecule}-irc_${3}-reverse/g" file-temp.com >> file-temp1.com
            sed -e "s/level_of_theory/${level_theory}/g" file-temp1.com >> file-temp2.com

            mv file-temp2.com ${folder_location}/6_prod-run_IRC/${new_filenamer}.com

            rm file-temp*.com

            ######## The section below creates the PBS file for submission on flux

            sed -e "s/molecule/${molecule}/g" $tpl/gaussian-PBS-tpl.txt > PBS-temp1.txt
            sed -e "s/study/${2}/g" PBS-temp1.txt >> PBS-temp2.txt
            sed -e "s/level_of_theory_short/${short_level_theory}/g" PBS-temp2.txt >> PBS-temp3.txt
            sed -e "s/conform/${new_filenamer}/g" PBS-temp3.txt > PBS-temp4.txt
            sed -e "s/gauss-log/${new_filenamer}_${3}/g" PBS-temp4.txt > ${folder_location}/6_prod-run_IRC/PBS-${2}-${new_filenamer}.txt

            rm PBS-temp*
        fi
    done
