#!/usr/bin/bash

# Created by: Stephen P. Vicchio

# The purpose of this script is to show the normal mode analysis from gaussian in a way
# that can be easiler seen.
#

molecule=${1}
job_type=${2}
level_theory=${3}

results_dirct=/home/vicchio/puckering/zz_results/2_bxyl
new_results=${molecule}-${job_type}-${level_theory}
out_dirct=9_hartree_norm

if [ "${molecule}" == 'oxane' ] ; then
    status_build=0
    mole_folder=1_oxane
elif [ "${molecule}" == 'bxyl' ] ;  then
	status_build=0
	mole_folder=2_bxyl
else
	echo
	echo "The molecule type is not found in this script"
	status_build=1
fi


if [ ${status_build} == "1" ]; then
	echo
	echo "Something isn't right with the script...the molecule"
	echo "may not be found!"
	echo
	exit
elif [ ${status_build} == "0" ]; then

    if [ ! -d ../${out_dirct} ]; then
        mkdir ../9_hartree_norm
    fi

    hartree norm -d ../8_norm/. -o ../9_hartree_norm/.

    if [ ! -d ${results_dirct}/${new_results}/ ]; then
        mkdir ${results_dirct}/${new_results}/
        mkdir mkdir ${results_dirct}/${new_results}/hartree-files
        mkdir  mkdir ${results_dirct}/${new_results}/log-files
    fi

    cp ../9_hartree_norm/*.txt ${results_dirct}/${new_results}/hartree-files
    cp ../8_norm/*.log ${results_dirct}/${new_results}/log-files
fi

# This part of the script will now look at the different outputs to ID which structures matter.

ts_hartree_file=/home/vicchio/puckering/zz_results/${mole_folder}/z_cluster-sorted-TS-${molecule}-${level_theory}.csv

input_list=$( column -t -s ',' ${ts_hartree_file} | awk '{print $1}' )

for file in ${input_list}; do

    file1=${file%.log\"}
    file_org=${file1##\"}

   if [ "${file_org}" != "File" ]; then

        raw_data=$(cat ../9_hartree_norm/${file_org}_norm-norm.txt | head -n 15 | tail -n 10)
        echo ""
        echo ${raw_data}
        echo
   fi
done
