#!/usr/bin/bash

input=$(head -n 1 y1-level_of_theory_basis_set.txt)
input_list=y0-input_list.txt

for file in $( <$input_list); do

	# This part of the script modifies the Gaussian Input (.com) file:                 
	sed -i "1s/.*/%chk=\/scratch\/hbmayes_fluxod\/vicchio\/${1}-${3}-${file}.chk/" ${file}.com
	sed -i "2s/.*/${input}/" ${file}.com
	sed -i "2s/$/\n/" ${file}.com 

	sed -i '$d' ${file}.com

	sed -i '$s/$/\nD   1    2    3    4 F/' ${file}.com
	sed -i '$s/$/\nD   2    3    4    5 F/' ${file}.com
	sed -i '$s/$/\nD   3    4    5    6 F/' ${file}.com
	sed -i '$s/$/\nD   4    5    6    1 F/' ${file}.com

	sed -i '$s/$/\n/' ${file}.com   
	sed -i '$s/$/\n/' ${file}.com

done 

